eConnect.Application/Controllers/ManageTechnicalSupportRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConnect.DataAccess;
using eConnect.Model;
using eConnect.Logic;
using System.IO;
using System.Configuration;
namespace eConnect.Application.Controllers
{
    public class ManageTechnicalSupportRequestController : Controller
    {
        string TechSupportPath = Convert.ToString(ConfigurationManager.AppSettings["TechFilePath"]);
        List<SelectListItem> Status = new List<SelectListItem>()
        {

            //new SelectListItem { Text = "Select Status", Value = "" },
            //        
            new SelectListItem { Text = "Open", Value = "1" },
            new SelectListItem { Text = "All", Value = "" },
            new SelectListItem { Text = "In-Progress", Value = "2" },
            new SelectListItem { Text = "Close", Value = "3" },
            new SelectListItem { Text = "Rejected", Value = "7" }


        };
        List<SelectListItem> City = new List<SelectListItem>()
        {

            new SelectListItem { Text = "Select City", Value = "" },
        };
        RaiseRequestLogic raiseRequest = new RaiseRequestLogic();

        public ActionResult Index()
        {
            BranchCodeLogic objBranchCodeLogic = new BranchCodeLogic();
            CategoryLogic objCategoryLogic = new CategoryLogic();
            UserLogic objUserDetailLogic = new UserLogic();
            StatusLogic objStatusLogic = new StatusLogic();
            StateLogic objStateLogic = new StateLogic();
            CityLogic objCityLogic = new CityLogic();
            ViewBag.State = new SelectList(objStateLogic.GetAllStates(), "StateId", "Name");
            ViewBag.City = City;
            ViewBag.Status = Status;
            ViewBag.BranchCode = new SelectList(objBranchCodeLogic.GetAllBranchCode(), "BranchCode", "BranchCode");
            ViewBag.Category = new SelectList(objCategoryLogic.GetAllCategory(), "Category", "Category");
            TechSupportProblemLogic techSupport = new TechSupportProblemLogic();
            var ProblemList = techSupport.GetAllTechSupportProblems();
            ViewBag.ProblemList = ProblemList;

            var tblTechDetails = raiseRequest.GetManageTechDetails(20, 1);
            bool flag = Convert.ToBoolean(TempData["flag"]);
            if (flag == true)
            {
                ViewBag.Record = Convert.ToInt32(TempData["Record"]);
                tblTechDetails = TempData["searchdataManageTech"] as List<sp_GetManageTechSupportRequestDetails_Result>;
            }
            else
            {
                ViewBag.Record = 20;

            }
            tblTechDetails = tblTechDetails.Where(w => w.TechRequestId == w.TechRequestId).Select(w => { w.Attachment = TechSupportPath.Replace("~", "") + w.TechRequestId + "\\TechSupportScreenshort\\" + w.AttachmentSource; return w; }).ToList();

            //ViewBag.Opencount = raiseRequest.GetManageTechDetails().Count(x => x.Status == 1);//Open
            //ViewBag.InProgresscount = raiseRequest.GetManageTechDetails().Count(x => x.Status == 2);//tblTechDetails.Count(x => x.Status == 2);//In-Progress
            //ViewBag.Closecount = raiseRequest.GetManageTechDetails().Count(x => x.Status == 3);//tblTechDetails.Count(x => x.Status == 3);//Close
            //ViewBag.Rejectcount = raiseRequest.GetManageTechDetails().Count(x => x.Status == 7);//tblTechDetails.Count(x => x.Status == 7);//Reject
            // return View(tblTechDetails.ToList().OrderByDescending(x => x.TechRequestId));
           return View(tblTechDetails.ToList().OrderBy(x => x.RequestedDate));
        }

        public ActionResult IndexSearch(string Requestid, string CspName, string CspID, string State, string City, string Status, string Requesteddte, string Completiondte, string BranchCode, string Category, string TechProblemType, string Record)
        {
            int Cid = 0, Sid = 0, Cityid = 0, Statusid = 0, ProblemType = 0;
            string Reqid = "";
            if (TechProblemType == "")
            {
                ProblemType = 0;
            }
            else
            {
                ProblemType = Convert.ToInt32(TechProblemType);
            }
            if (CspID == "")
            {
                Reqid = "0";
            }
            else
            {
                Reqid = CspID;
            }
            //if (Requestid == "")
            //{
            //    Reqid = 0;
            //}
            //else
            //{
            //    Reqid = Convert.ToInt32(Requestid);
            //}
            //if (BranchCode == "" || BranchCode == "Select BranchCode")
            //{
            //    Bcode = 0;
            //}
            //else
            //{
            //    Bcode = Convert.ToInt32(BranchCode);
            //}
            //if (Category == "" || Category == "Select Category")
            //{
            //    CategoryId = 0;
            //}
            //else
            //{
            //    CategoryId = Convert.ToInt32(Category);
            //}
            //if (CspID == "")
            //{
            //    Cid = 0;
            //}
            //else
            //{
            //    Cid = Convert.ToInt32(CspID);
            //}
            if (State == "")
            {
                Sid = 0;
            }
            else
            {
                Sid = Convert.ToInt32(State);
            }
            if (City == "" || City == "---Select---")
            {
                Cityid = 0;
            }
            else
            {
                Cityid = Convert.ToInt32(City);
            }
            if (Status == "")
            {
                Statusid = 0;
            }
            else
            {
                Statusid = Convert.ToInt32(Status);
            }
            var tblManageTechDetails = raiseRequest.GetManageTechDetailsSearch(Reqid, CspName, Cid, Sid, Cityid, Statusid, Requesteddte, Completiondte, BranchCode, Category, ProblemType, Convert.ToInt32(Record));
            TempData["searchdataManageTech"] = tblManageTechDetails.ToList();
            TempData["flag"] = true;
            Session["status"] = Statusid;
            TempData["Record"] = Convert.ToInt32(Record);
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)

        {
            TechSupportProblemLogic techSupport = new TechSupportProblemLogic();
            RaiseRequestLogic raiseRequestdetals = new RaiseRequestLogic();
            ManageTechSupport objMTech = raiseRequestdetals.GetManageTechDetailByID((int)id);
            var Status = new[]
            {

                 new SelectListItem { Text = "Select Status", Value = "" },
                  new SelectListItem { Text = "Open", Value = "1" },
                   new SelectListItem { Text = "In-Progress", Value = "2" },
                 new SelectListItem { Text = "Close", Value = "3" },
                 new SelectListItem { Text = "Rejected", Value = "7" }

            };
            var selectedStatus = Status.FirstOrDefault(d => d.Value == objMTech.CurrentStatus.ToString());
            if (selectedStatus != null)
                selectedStatus.Selected = true;
            ViewBag.EditedStatus = Status;
            var ProblemList = techSupport.GetAllTechSupportProblems();
            ViewBag.ProblemList = ProblemList;

            return View(objMTech);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ManageTechSupport tech)
        {
            RaiseRequestLogic raiseRequestLogic = new RaiseRequestLogic();
            raiseRequestLogic.UpdateManageTechDetail(tech);
            TempData["Message"] = "Record submitted successfully";
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            TechSupportProblemLogic techSupport = new TechSupportProblemLogic();
            RaiseRequestLogic raiseRequestdetals = new RaiseRequestLogic();
            ManageTechSupport objMTech = raiseRequestdetals.GetManageTechDetailByID((int)id);
            var Status = new[]
            {

                 new SelectListItem { Text = "Select Status", Value = "" },
                  new SelectListItem { Text = "Open", Value = "1" },
                   new SelectListItem { Text = "In-Progress", Value = "2" },
                 new SelectListItem { Text = "Close", Value = "3" },
                 new SelectListItem { Text = "Rejected", Value = "7" }

            };
            var selectedStatus = Status.FirstOrDefault(d => d.Value == objMTech.CurrentStatus.ToString());
            if (selectedStatus != null)
                selectedStatus.Selected = true;
            ViewBag.EditedStatus = Status;
            var ProblemList = techSupport.GetAllTechSupportProblems();
            ViewBag.ProblemList = ProblemList;

            return View(objMTech);
        }
    }
}

eConnect.Application/Views/ManageTechnicalSupportRequest/Details.cshtml
@model eConnect.Model.ManageTechSupport
@{ ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";

    string Receipt =  Model.Id + "/TechSupportScreenshort/" + Model.Recieptpic;
    }
@*<h2></h2>*@
<section class="section">
    <div class="card">
        <div class="card-body">
            <h6 class="text-primary mb-3"> Request Detail</h6>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProblemType, htmlAttributes: new { @class = "required-field" })
                        @Html.DropDownList("TechProblemType", new SelectList(ViewBag.ProblemList, "ProblemTypeId", "Name"), new { id = "TechProblemType", @class = "form-control", @readonly = "readonly" })

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RequestedDate, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.RequestedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CurrentStatus, htmlAttributes: new { @class = "" })
                        @Html.DropDownList("Status", (SelectListItem[])ViewBag.EditedStatus, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CompletionDate, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.CompletionDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.AnyDeskDetails, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.AnyDeskDetails, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                @*</div>*@

            </div>

            <h6 class="text-primary mb-3"> Resolution Detail</h6>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ScreenShot, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.Recieptpic, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                        @if (!string.IsNullOrEmpty(Model.Recieptpic))
                        {
                        @*<a href="javascript:PreviewImage('@Model.Recieptpic');">PreviewImage</a>*@ 
                        <a href="~/ImageViewer/Getimage/?Type=Tech+&File=+@Receipt" target="_blank">PreviewImage</a>
                        
                        }
                        else
                        {
                            <span style="color:red;">No image uploaded.</span>}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ResolutionDetail, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.ResolutionDetail, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

            </div>
            @*<div class="my-4 text-right">
                    <button class="btn btn-primary px-4" type="submit">Save</button>
                </div>*@

        </div>
    </div>
    <div class="my-4 text-right">
        @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
    </div>
</section>
<script>
    debugger;
    function PreviewImage(url) {
        var win = window.open();
        win.document.write("<iframe width='100%' height='100%' scrolling='no' src='" + url + "'></iframe>");
    }
</script>

eConnect.Application/Views/ManageTechnicalSupportRequest/Edit.cshtml
@model eConnect.Model.ManageTechSupport

@{ ViewBag.Title = "Edit Technical Support Request";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    string Receipt =  Model.Id + "/TechSupportScreenshort/" + Model.Recieptpic;
    //string Receipt = @System.Web.Configuration.WebConfigurationManager.AppSettings["TechFilePath"] + Model.Id + "\\TechSupportScreenshort\\" + Model.Recieptpic;

    }

@*<h2></h2>*@

@using (Html.BeginForm("Edit", "ManageTechnicalSupportRequest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)
                                                <section class="section">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            @*<h6 class="text-primary mb-3"> Request Detail</h6>*@
                                                            <div class="row">

                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>

                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.ProblemType, htmlAttributes: new { @class = "required-field" })
                                                                        @Html.DropDownList("TechProblemType", new SelectList(ViewBag.ProblemList, "ProblemTypeId", "Name"), new { id = "TechProblemType", @class = "form-control", disabled = "disabled" })

                                                                    </div>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>

                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.RequestedDate, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.RequestedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.CurrentStatus, htmlAttributes: new { @class = "" })
                                                                        @Html.DropDownList("CurrentStatus", (SelectListItem[])ViewBag.EditedStatus, htmlAttributes: new { @class = "form-control"})
                                                                    </div>
                                                                </div>


                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.CompletionDate, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.CompletionDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.AnyDeskDetails, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.AnyDeskDetails, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                    </div>
                                                                </div>
                                                                @*</div>*@

                                                            </div>

                                                            <h6 class="text-primary mb-3"> Action</h6>
                                                            <div class="row">
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.ScreenShot, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.Recieptpic, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                                                        @if (!string.IsNullOrEmpty(Model.Recieptpic))
                                                                        {
                                                                            @*<a href="javascript:PreviewImage('@Model.Recieptpic');">PreviewImage</a>*@
                                                                            <a href="~/ImageViewer/Getimage/?Type=Tech+&File=+@Receipt" target="_blank">PreviewImage</a>
                                                                        }
                                                                        else
                                                                        {
                                                                            <span style="color:red;">No image uploaded.</span>}
                                                                    </div>
                                                                </div>


                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "" })
                                                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", } })

                                                                    </div>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.ResolutionDetail, htmlAttributes: new { @class = "required-field" })
                                                                        @Html.EditorFor(model => model.ResolutionDetail, new { htmlAttributes = new { @class = "form-control", @style = "height:80px" } })

                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="my-4 text-right">
                                                                <button class="btn btn-primary px-4" type="submit">Save</button> |  @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                                                            </div>
                                                            @*<div class="text-left">
                                                                @Html.ActionLink("Cancel", "Index")
                                                            </div>*@
                                                        </div>
                                                    </div>
                                                </section>}
<script>
    debugger;
    function PreviewImage(url) {
        var win = window.open();
        win.document.write("<iframe width='100%' height='100%' scrolling='no' src='" + url + "'></iframe>");
    }
</script>