eConnect.Application/Controllers/DownloadDocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConnect.DataAccess;
using eConnect.Logic;
using eConnect.Model;

namespace eConnect.Application.Controllers
{
    public class DownloadDocumentController : Controller
    {
        private eConnectAppEntities db = new eConnectAppEntities();
        List<SelectListItem> DocumenStatusList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Active", Value = "True" },
                new SelectListItem { Text = "InActive", Value = "False" },

            };
        // GET: DownloadDocument
        public ActionResult Index()
        {
            DownloadDocumentLogic objDownloadDocumentLogic = new DownloadDocumentLogic();
            return View(objDownloadDocumentLogic.GeAllDownloadDocument());
        }

        // GET: DownloadDocument/Details/5
        public ActionResult Details(byte? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDownloadDetail tblDownloadDetail = db.tblDownloadDetails.Find(id);
            if (tblDownloadDetail == null)
            {
                return HttpNotFound();
            }
            return View(tblDownloadDetail);
        }

        // GET: DownloadDocument/Create
        public ActionResult Create()
        {
            ViewBag.Status = new SelectList(DocumenStatusList, "Value", "Text");
            return View();
        }

        // POST: DownloadDocument/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DownloadDocumentDetailModel DownloadDocumentDetailModel)
        {
            if (ModelState.IsValid)
            {
                if (DownloadDocumentDetailModel.DocumentImage !=null)
                { 
                DownloadDocumentLogic objDownloadDocumentLogic = new DownloadDocumentLogic();
                //string FilePath = System.Web.HttpContext.Current.Server.MapPath("~/Content/EgraminAssets\assets/DownloadsDocuments/");
                DownloadDocumentDetailModel.DocumentPath = Path.Combine("~\\Content\\EgraminAssets\\assets\\DownloadsDocuments", DownloadDocumentDetailModel.DocumentImage.FileName);
                string path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/EgraminAssets/assets/DownloadsDocuments"), Path.GetFileName(DownloadDocumentDetailModel.DocumentImage.FileName));
                if (DownloadDocumentDetailModel.DocumentImage != null)
                {
                    DownloadDocumentDetailModel.DocumentImage.SaveAs(path);
                }
                objDownloadDocumentLogic.InsertDownloadDocument(DownloadDocumentDetailModel);
                return RedirectToAction("Index");
                }
            }
            //ViewBag.Status = DocumenStatusList;
            ViewBag.Status = new SelectList(DocumenStatusList, "Value", "Text", DownloadDocumentDetailModel.Status);
            return View(DownloadDocumentDetailModel);
        }

        // GET: DownloadDocument/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DownloadDocumentLogic objDownloadDocumentLogic = new DownloadDocumentLogic();
           var data= objDownloadDocumentLogic.GetDownloadDocumentByID((int)id);
            if (data == null)
            {
                return HttpNotFound();
            }
            ViewBag.Status = new SelectList(DocumenStatusList, "Value", "Text", data.Status);
            return View(data);
        }

        // POST: DownloadDocument/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DownloadDocumentDetailModel DownloadDocumentDetailModel)
        {
            if (ModelState.IsValid)
            {
                DownloadDocumentLogic objDownloadDocumentLogic = new DownloadDocumentLogic();
                if (DownloadDocumentDetailModel.DocumentImage != null)
                {
                    
                    //string FilePath = System.Web.HttpContext.Current.Server.MapPath("~/Content/EgraminAssets\assets/DownloadsDocuments/");
                    DownloadDocumentDetailModel.DocumentPath = Path.Combine("~\\Content\\EgraminAssets\\assets\\DownloadsDocuments", DownloadDocumentDetailModel.DocumentImage.FileName);
                    string path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/EgraminAssets/assets/DownloadsDocuments"), Path.GetFileName(DownloadDocumentDetailModel.DocumentImage.FileName));
                    if (DownloadDocumentDetailModel.DocumentImage != null)
                    {
                        DownloadDocumentDetailModel.DocumentImage.SaveAs(path);
                    }
                }
                objDownloadDocumentLogic.UpdateDownloadDocument(DownloadDocumentDetailModel);               
                return RedirectToAction("Index");
            }
            ViewBag.Status = new SelectList(DocumenStatusList, "Value", "Text", DownloadDocumentDetailModel.Status);
            return View(DownloadDocumentDetailModel);
        }

        // GET: DownloadDocument/Delete/5
        public ActionResult Delete(byte? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDownloadDetail tblDownloadDetail = db.tblDownloadDetails.Find(id);
            if (tblDownloadDetail == null)
            {
                return HttpNotFound();
            }
            return View(tblDownloadDetail);
        }

        // POST: DownloadDocument/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(byte id)
        {
            tblDownloadDetail tblDownloadDetail = db.tblDownloadDetails.Find(id);
            db.tblDownloadDetails.Remove(tblDownloadDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
     
    }
}

eConnect.Application/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConnect.DataAccess;
using eConnect.Logic;
using NLog;
namespace eConnect.Application.Controllers
{
    public class MenuController : Controller
    {
        private static Logger logger = LogManager.GetLogger("EConnectLogRules");
        private eConnectAppEntities db = new eConnectAppEntities();
         
        // GET: tblMenuSubs
        List<SelectListItem> menuStatus = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Active", Value = "True" },
                new SelectListItem { Text = "InActive", Value = "False" },

            };
        // GET: Menu
        public ActionResult Index()
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            var menuData = objMenuLogic.GetAllSubMain(); 
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text");         
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle");
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name");
            return View(menuData.ToList());
        }
        public ActionResult IndexSearch(int? MenuMainId, int? RoleId, string ScreenTittle, bool? Status)
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            var menuData = objMenuLogic.GetAllSubMainDetailSearch(MenuMainId,RoleId, ScreenTittle, Status);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text");
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle");
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name");
            return View("Index", menuData.ToList());
        }

        // GET: tblMenuSubs/Details/5
        public ActionResult Details(int id)
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
         
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMenuSub tblMenuSub = objMenuLogic.GetSubMainById(id);
            if (tblMenuSub == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name", tblMenuSub.RoleId);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text", tblMenuSub.Status);
            return View(tblMenuSub);
        }

        // GET: tblMenuSubs/Create
        public ActionResult Create()
        {
            try
            {
                MenuLogic objMenuLogic = new MenuLogic();
                RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
                ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle");
                ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name");
                ViewBag.Status = new SelectList(menuStatus, "Value", "Text");
            }
            catch(Exception ex)
            {
                logger.Error("Create Menu Create" + " " + ex.Message);

            }

            return View();
        }

        // POST: tblMenuSubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tblMenuSub tblMenuSub)
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            if (ModelState.IsValid)
            {               
                objMenuLogic.InsertSubMainWithMenuMenu(tblMenuSub);               
                return RedirectToAction("Index");
            }

            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name", tblMenuSub.RoleId);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text", tblMenuSub.Status);
            return View(tblMenuSub);
        }

        // GET: tblMenuSubs/Create
        public ActionResult CreateNew()
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle");
            ViewBag.MenuSubId = new SelectList(objMenuLogic.GetAllSubMain(), "MenuSubId", "Tittle");
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name");
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text");
            return View();
        }

        // POST: tblMenuSubs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew(tblMenuSub tblMenuSub)
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            if (ModelState.IsValid)
            {
                tblMenuSub.Controller = objMenuLogic.GetSubMainById(tblMenuSub.MenuSubId).Controller.ToString();
                tblMenuSub.Action = objMenuLogic.GetSubMainById(tblMenuSub.MenuSubId).Action.ToString();
                tblMenuSub.Tittle = objMenuLogic.GetSubMainById(tblMenuSub.MenuSubId).Tittle.ToString();
                objMenuLogic.InsertSubMainWithMenuMenu(tblMenuSub);
                return RedirectToAction("Index");
            }

            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);
            ViewBag.MenuSubId = new SelectList(objMenuLogic.GetAllSubMain(), "MenuSubId", "Tittle");
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name", tblMenuSub.RoleId);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text", tblMenuSub.Status);
            return View(tblMenuSub);
        }

        public ActionResult EditNew(int id)
        {

            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMenuSub tblMenuSub = objMenuLogic.GetSubMainById(id);
            if (tblMenuSub == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);
            ViewBag.MenuSubIdSelect = new SelectList(objMenuLogic.GetAllSubMain(), "MenuSubId", "Tittle", tblMenuSub.MenuSubId);
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name", tblMenuSub.RoleId);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text", tblMenuSub.Status);
            return View(tblMenuSub);
        }

        // POST: tblMenuSubs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditNew(tblMenuSub tblMenuSub, int MenuSubIdSelect)
        {
            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            if (ModelState.IsValid)
            {
                tblMenuSub.Controller = objMenuLogic.GetSubMainById(MenuSubIdSelect).Controller.ToString();
                tblMenuSub.Action = objMenuLogic.GetSubMainById(MenuSubIdSelect).Action.ToString();
                tblMenuSub.Tittle = objMenuLogic.GetSubMainById(MenuSubIdSelect).Tittle.ToString();
                objMenuLogic.UpdateSubMainWithMenuMenu(tblMenuSub);
                return RedirectToAction("Index");
            }
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);
            ViewBag.MenuSubIdSelect = new SelectList(objMenuLogic.GetAllSubMain(), "MenuSubId", "Tittle", tblMenuSub.MenuSubId);
            ViewBag.RoleId = new SelectList(objRoleMasterLogic.GetAllRoles(), "RoleId", "Name", tblMenuSub.RoleId);
            ViewBag.Status = new SelectList(menuStatus, "Value", "Text", tblMenuSub.Status);
            return View(tblMenuSub);
        }

        // GET: tblMenuSubs/Edit/5
        public ActionResult Edit(int id)
        {

            MenuLogic objMenuLogic = new MenuLogic();
            RoleMasterLogic objRoleMasterLogic = new RoleMasterLogic();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMenuSub tblMenuSub = objMenuLogic.GetSubMainById(id);
            if (tblMenuSub == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuMainId = new SelectList(objMenuLogic.GetAllMainMenu(), "MenuMainId", "Tittle", tblMenuSub.MenuMainId);          

eConnect.Application/Views/DownloadDocument/Create.cshtml
@model eConnect.Model.DownloadDocumentDetailModel

@{
    ViewBag.Title = "Download Document";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


@using (Html.BeginForm("Create", "DownloadDocument", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <section class="section">
        <div class="card">
            <div class="card-body">
            
                <div class="row">

                    <div class="col-md-4">
                        @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                        @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "required-field" })
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-group">
                                @Html.LabelFor(model => model.DocumentStatus, htmlAttributes: new { @class = "required-field" })
                                @Html.DropDownList("Status", ViewBag.Status as SelectList, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DocumentStatus, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DocumentImage, htmlAttributes: new { @class = "" })
                            <input type="file" id="DocumentImage" name="DocumentImage" class="btn btn-outline-primary btn-block fileup-btn" onchange="showDocument(this)" />
                            @Html.ValidationMessageFor(model => model.DocumentImage, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    <div class="my-4 text-right">
                        <button class="btn btn-primary px-4" type="submit">Save</button> |
                        @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                        
                    </div>
                </div>
        </div>
            </div>
    </section>}



@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

eConnect.Application/Views/DownloadDocument/Delete.cshtml
@model eConnect.DataAccess.tblDownloadDetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblDownloadDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocumentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eConnect.Application/Views/DownloadDocument/Edit.cshtml
@model eConnect.Model.DownloadDocumentDetailModel

@{
    ViewBag.Title = "Download Document";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


@using (Html.BeginForm("Edit", "DownloadDocument", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.DocumentPath)
    @Html.HiddenFor(model => model.DocumentStatus)
    <section class="section">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                        @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "required-field" })
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-group">
                                @Html.LabelFor(model => model.DocumentStatus, htmlAttributes: new { @class = "required-field" })
                                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DocumentImage, htmlAttributes: new { @class = "" })
                            <input type="file" id="DocumentImage" name="DocumentImage" class="btn btn-outline-primary btn-block fileup-btn" onchange="show(this)" />
                            @Html.ValidationMessageFor(model => model.DocumentImage, "", new { @class = "text-danger" })
                            @if (!string.IsNullOrEmpty(Model.DocumentPath))
                            {
                                <a href="@Url.Content(Model.DocumentPath)" target="_blank">PreviewImage</a>
                            }
                            else
                            { <span style="color:red;">No image uploaded.</span>
                            }
                        </div>
                    </div>

                    <div class="my-4 text-right">
                        <button class="btn btn-primary px-4" type="submit">Save</button> |
                        @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                    </div>
                </div>
            </div>
        </div>
    </section>}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

eConnect.Application/Views/DownloadDocument/Index.cshtml
@model IEnumerable<eConnect.DataAccess.tblDownloadDetail>

@{
    ViewBag.Title = "Download Document";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}



<p>
    
    @Html.ActionLink("Create New", "Create", "Menu", new { @class = "btn btn-primary px-4" })
</p>
<section class="section">

    <div class="card">

        <div class="card-body">

            <div class="table-responsive">
                <div class="table-actions">
                </div>
                <table class="table table-striped" id="table-2">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.DocumentName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Priority)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Status)
                            </th>

                            <th> Action </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.DocumentName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Priority)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>