eConnect.Application/Controllers/ManageDepositRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConnect.DataAccess;
using eConnect.Model;
using eConnect.Logic;
using System.IO;
using System.Configuration;

namespace eConnect.Application.Controllers
{
    public class ManageDepositRequestController : Controller
    {
        // GET: ManageWithdrawalRequest
        string ReceiptPath = Convert.ToString(ConfigurationManager.AppSettings["DepositFilePath"]);
        List<SelectListItem> Status = new List<SelectListItem>()
            {
                //new SelectListItem { Text = "Select Status", Value = "" },
                new SelectListItem { Text = "Open", Value = "1" },
                 new SelectListItem { Text = "All", Value = "" },
                 new SelectListItem { Text = "Close", Value = "3" },
                 new SelectListItem { Text = "Rejected", Value = "7" }
            };
        List<SelectListItem> City = new List<SelectListItem>()
            {

                new SelectListItem { Text = "Select City", Value = "" },
            };
        RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
        public ActionResult Index()
        {
            BranchCodeLogic objBranchCodeLogic = new BranchCodeLogic();
            CategoryLogic objCategoryLogic = new CategoryLogic();
            UserLogic objUserDetailLogic = new UserLogic();
            StatusLogic objStatusLogic = new StatusLogic();
            StateLogic objStateLogic = new StateLogic();
            CityLogic objCityLogic = new CityLogic();
            ViewBag.State = new SelectList(objStateLogic.GetAllStates(), "StateId", "Name");
            ViewBag.City = City;
            ViewBag.Status = Status;
            ViewBag.BranchCode = new SelectList(objBranchCodeLogic.GetAllBranchCode(), "BranchCode", "BranchCode");
            ViewBag.Category = new SelectList(objCategoryLogic.GetAllCategory(), "Category", "Category");

            var tblDepositDetails = raiseRequest.GetManageDepositDetails(20, 1);
            bool flag = Convert.ToBoolean(TempData["flag"]);
            if (flag == true)
            {
                ViewBag.Record = Convert.ToInt32(TempData["Record"]);
                tblDepositDetails = TempData["searchdataManagedeposit"] as List<sp_GetManageDepositRequestDetails_Result>;
            }
            else
            {
                ViewBag.Record = 20;
            }
            tblDepositDetails = tblDepositDetails.Where(w => w.DepositeRequestId == w.DepositeRequestId).Select(w => { w.ReceiptSource = ReceiptPath.Replace("~", "") + w.DepositeRequestId + "\\DepositReceipt\\" + w.ReceiptSource; return w; }).ToList();

            //ViewBag.Opencount = raiseRequest.GetManageDepositDetails().Count(x => x.Status == 1);//Open
            ////ViewBag.InProgresscount = tblDepositDetails.Count(x => x.Status == 2);//In-Progres
            //ViewBag.Closecount = raiseRequest.GetManageDepositDetails().Count(x => x.Status == 3);//Close
            //ViewBag.Rejectcount = raiseRequest.GetManageDepositDetails().Count(x => x.Status == 7);//Reject

            // return View(tblDepositDetails.ToList().OrderByDescending(x => x.DepositeRequestId));
            return View(tblDepositDetails.ToList());
        }
        public ActionResult IndexSearch(string Requestid, string CspName, string CspID, string State, string City, string Status, string Requesteddte, string Completiondte, string BranchCode, string Category, string Depositdte, string Record)
        {
            int Cid = 0, Sid = 0, Cityid = 0, Statusid = 0, Bcode = 0, CategoryId = 0;
            string Reqid = "";
            if (CspID == "")
            {
                Reqid = "0";
            }
            else
            {
                Reqid = CspID;
            }
            //if (BranchCode == "" || BranchCode == "Select BranchCode")
            //{
            //    Bcode = 0;
            //}
            //else
            //{
            //    Bcode = Convert.ToInt32(BranchCode);
            //}
            //if (Category == "" || Category == "Select Category")
            //{
            //    CategoryId = 0;
            //}
            //else
            //{
            //    CategoryId = Convert.ToInt32(Category);
            //}
            //if (CspID == "")
            //{
            //    Cid = 0;
            //}
            //else
            //{
            //    Cid = Convert.ToInt32(CspID);
            //}
            if (State == "")
            {
                Sid = 0;
            }
            else
            {
                Sid = Convert.ToInt32(State);
            }
            if (City == "" || City == "---Select---")
            {
                Cityid = 0;
            }
            else
            {
                Cityid = Convert.ToInt32(City);
            }
            if (Status == "")
            {
                Statusid = 0;
            }
            else
            {
                Statusid = Convert.ToInt32(Status);
            }
            var tblManageDepositDetails = raiseRequest.GetManageDepositDetailsSearch(Reqid, CspName, Cid, Sid, Cityid, Statusid, Requesteddte, Completiondte, BranchCode, Category, Depositdte, Convert.ToInt32(Record));
            TempData["searchdataManagedeposit"] = tblManageDepositDetails.ToList();
            TempData["flag"] = true;
            Session["status"] = Statusid;
            TempData["Record"] = Convert.ToInt32(Record);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {

            RaiseRequestLogic raiseRequestdetals = new RaiseRequestLogic();
            ManageDeposit objMDeposit = raiseRequestdetals.GetManageDepositDetailByID((int)id);
            var Status = new[]
            {

                 new SelectListItem { Text = "Select Status", Value = "" },
                  new SelectListItem { Text = "Open", Value = "1" },
                 new SelectListItem { Text = "Close", Value = "3" },
                 new SelectListItem { Text = "Rejected", Value = "7" }

            };
            var selectedStatus = Status.FirstOrDefault(d => d.Value == objMDeposit.CurrentStatus.ToString());
            if (selectedStatus != null)
                selectedStatus.Selected = true;
            ViewBag.EditedStatus = Status;
            return View(objMDeposit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ManageDeposit deposit)
        {
            RaiseRequestLogic raiseRequestLogic = new RaiseRequestLogic();
            raiseRequestLogic.UpdateManageDepositDetail(deposit);
            TempData["Message"] = "Record submitted successfully";
            return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            RaiseRequestLogic raiseRequestdetals = new RaiseRequestLogic();
            ManageDeposit objMDeposit = raiseRequestdetals.GetManageDepositDetailByID((int)id);
            //raiseRequestdetals.GetManageDepositDetailByID((int)id);
            var Status = new[]
            {

                 new SelectListItem { Text = "Select Status", Value = "" },
                  new SelectListItem { Text = "Open", Value = "1" },
                 new SelectListItem { Text = "Close", Value = "3" },
                 new SelectListItem { Text = "Rejected", Value = "7" }

            };
            var selectedStatus = Status.FirstOrDefault(d => d.Value == objMDeposit.CurrentStatus.ToString());
            if (selectedStatus != null)
                selectedStatus.Selected = true;
            ViewBag.EditedStatus = Status;
            return View(objMDeposit);
        }




        [HttpPost]
        //*******************For Deposit/Withdraw/Techsupport Status Update**************************************//
        public JsonResult UpdateRequestStatus(int RequestId, string status, string Comments, string RequestType)
        {
            RaiseRequestLogic requestLogic = new RaiseRequestLogic();
            try
            {
                requestLogic.UpdateRequestDetailsStatus(RequestId, status, Comments, RequestType);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        //*******************For Configure/Make/Authorize Status Update**************************************//
        public JsonResult UpdateConfigure_Make_Authorize(int RequestId, string Configure, string Make, string Authorize)
        {
            RaiseRequestLogic requestLogic = new RaiseRequestLogic();
            try
            {
                requestLogic.UpdateConfigure_Make_AuthorizeStatus(RequestId, Configure, Make, Authorize);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        //*******************For Configure/Make/Authorize Status Update**************************************//
        public JsonResult UpdateConfigure_Make_Authorize_AutAmount(int RequestId, string Configure, string Make, string Authorize, decimal AutAmount)
        {
            RaiseRequestLogic requestLogic = new RaiseRequestLogic();
            try
            {
                requestLogic.UpdateConfigure_Make_AuthorizeStatus_AutAmount(RequestId, Configure, Make, Authorize, AutAmount);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

eConnect.Application/Controllers/PartialController.cs
using eConnect.Application.Models;
using eConnect.DataAccess;
using eConnect.Logic;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eConnect.Application.Controllers
{
    public class PartialController : Controller
    {
        private eConnectAppEntities db = new eConnectAppEntities();


        /// <summar-eGramin>

        // GET: Partial
        [ChildActionOnly]
        public ActionResult GetNotification()
        {
            var NotificationSubject = db.tblNotifications.Where(d => d.Status == true).Select(d => d.NotificationSubject).FirstOrDefault();
            ViewBag.NotificationSubject = NotificationSubject;
            return View();
        }

        [ChildActionOnly]
        public ActionResult GetNotificationDetails()
        {
            var NotificationDetails = db.tblNotifications.Where(d => d.Status == true).Select(d => d.NotificationDetails).FirstOrDefault();
            ViewBag.NotificationDetails = NotificationDetails;
            return View();
        }
        [ChildActionOnly]
        public ActionResult GetGalleryImagesForTittle(int? id)
        {
            try
            {


                tblGalleryCategory tblGalleryCategory = db.tblGalleryCategories.Find(id);
                var fileCount = Directory.EnumerateFiles(AppDomain.CurrentDomain.BaseDirectory + tblGalleryCategory.CategoryImagesPath.ToString()).Count();
                List<string> getImgesList = new List<string>();
                if (fileCount > 0)
                {
                    getImgesList = Directory.GetFiles(AppDomain.CurrentDomain.BaseDirectory + tblGalleryCategory.CategoryImagesPath.ToString(), "*.jpg", SearchOption.AllDirectories).Take(4).ToList();
                    List<string> ImgesListWithPath = new List<string>();
                    foreach (string file in getImgesList)
                    {
                        var fileName = Path.GetFileName(file);
                        ImgesListWithPath.Add("~\\" + tblGalleryCategory.CategoryImagesPath.ToString() + "\\" + fileName);
                    }
                    ViewBag.ImgesListWithPath = ImgesListWithPath;
                }
                return View();
            }
            catch (Exception ex)
            {

                return View();
            }

        }
        [ChildActionOnly]
        public ActionResult GetLatestNewsForHome()
        {
            return View(db.tblLatestNews.Where(d => d.Status == true).OrderBy(d => d.Priority).Take(3).ToList());
        }

        [ChildActionOnly]
        public ActionResult GetSubNewsForNewsDetails()
        {
            return View(db.tblLatestNews.Where(d => d.Status == true).OrderBy(d => d.Priority).Take(5).ToList());
        }
        /// </summary-eGramin>
        /// <returns></returns>
        // GET: Partial
        [ChildActionOnly]
        public ActionResult _GetAppMenu()
        {
            if (Session != null && Session["UserTypeId"] != null)
            {
                int UserTypeId = (int)Session["UserTypeId"];
                MenuLogic objMenuLogic = new MenuLogic();
                var data = objMenuLogic.GetAllMenuMainWithSubMenuByRoleId(UserTypeId);
                if (!(data == null))
                {
                    return View(data);
                }
            }
            return View();
        }
        [ChildActionOnly]
        public ActionResult _GetAnnouncementMessage()
        {
            AnnouncementLogic objAnnouncementLogic = new AnnouncementLogic();
            ViewBag.AnnouncementMessage = objAnnouncementLogic.GetAnnouncementMessage();
            return View();
        }

        [ChildActionOnly]
        public ActionResult _GetAnnouncementDetail()
        {
            AnnouncementLogic objAnnouncementLogic = new AnnouncementLogic();
            ViewBag.AnnouncementDetail = objAnnouncementLogic.GetAnnouncementDetail();
            return View();
        }
        // GET: Partial
        public ActionResult Index()
        {
            return View();
        }

        // GET: Partial/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Partial/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Partial/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partial/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Partial/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partial/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Partial/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        [ChildActionOnly]
        public ActionResult _GetActiveWindow()
        {
            WindowTimingLogic wTiming = new WindowTimingLogic();
            ViewBag.ActiveWindow = wTiming.GetCurrentActiveWindow();







            //WindowTimingLogic OtrLogic = new WindowTimingLogic();
            //var dt = OtrLogic.GetCurrentActiveWindow();
            //DateTime dtStart = Convert.ToDateTime(dt[0].StartTime);
            //DateTime dtEnd = Convert.ToDateTime(dt[0].EndTime);
            //DateTime current = DateTime.Now;
            //DepositStartTime = dt[0].StartTime;
            //DepositEndTime = dt[0].EndTime;
            return View();
        }
    }
}

eConnect.Application/Views/ManageDepositRequest/Create.cshtml
@model eConnect.Model.Deposit

@{ ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml"; }



@using (Html.BeginForm("Create", "DepositRequest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <section class="section">
        <div class="card">
            <div class="card-body">
                @*<h6 class="text-primary mb-3"> Personal Details</h6>*@
                <div class="row">

                    @*<div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "required-field" })
                                @Html.DropDownList("RequestType", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "required-field" })
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @maxlength = "10" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "required-field" })
                                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>*@
                    @*<div class="row">*@
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.BankDepositReceipt, htmlAttributes: new { @class = "required-field" })
                            <input type="file" id="Reciept" name="Reciept" class="btn btn-outline-primary btn-block fileup-btn" onchange="show(this)" />
                            @Html.ValidationMessageFor(model => model.Reciept, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.BankDepositDate, htmlAttributes: new { @class = "required-field" })
                            <input type="date" id="BankDepositDate" name="BankDepositDate" class="form-control" />
                            @Html.ValidationMessageFor(model => model.BankDepositDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="my-4 text-right">
                    <center style="text-align:center;vertical-align:top;">
                        @{ Html.RenderAction("_GetActiveWindow", "Partial"); }
                    </center>
                        <button class="btn btn-primary px-4" type="submit">Save</button> |   @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                </div>
                <div>
                    <center>
                        <span style="color: blue;text-decoration: blink; ">@TempData["TimingWindowMessage"]</span>
                    </center>
                </div>
            </div>
        </div>
    </section>
}
@if (TempData["Message"] != null)
{
    <script type="text/javascript">
        $(function () {
            alert("@TempData["Message"]")
        });
    </script>
}
@if (TempData["TimingWindowMessage"] != null)
{
    <script type="text/javascript">
        $(function () {
            alert("@TempData["TimingWindowMessage"]")
        });
    </script>
}

eConnect.Application/Views/ManageDepositRequest/Delete.cshtml
@model eConnect.Model.Deposit

@{ ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutMain.cshtml"; @*string PassportSizePhotoPath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\PassportSizePhoto\\" + Model.PassportSizePhotoName;
        string VoterIdImagePath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\VoterIdImage\\" + Model.VoterIdImageName;
        string PANImagePath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\PANImage\\" + Model.PANImageName;
        string AadharImagePath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\AadharImage\\" + Model.AadharImageName;
        string LatestEducationProofImagePath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\LatestEducationProofImage\\" + Model.LatestEducationProofImageName;
        string IIBFCertificationImagePath = @System.Web.Configuration.WebConfigurationManager.AppSettings["CSPFilePath"] + Model.CSPId + "\\IIBFCertificationImage\\" + Model.IIBFCertificationImageName;
        }*@ }
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<section class="section">
    <div class="card">
        <div class="card-body">
            @*<h6 class="text-primary mb-3"> Personal Details</h6>*@
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "required-field" })
                        @*@Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })*@
                        @Html.DropDownList("RequestTypes", (SelectListItem[])ViewBag.RequestType, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @maxlength = "10", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "required-field" })
                        @Html.DropDownList("Status", (SelectListItem[])ViewBag.EditStatus, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                @*<div class="row">*@
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Reciept, htmlAttributes: new { @class = "required-field" })
                        @Html.EditorFor(model => model.Recieptpic, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                    </div>
                </div>

                @*</div>*@

            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger px-4" /> |
            @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
        </div>}
            @*<div class="text-left">
                @Html.ActionLink("Cancel", "Index")
            </div>*@
        </div>
    </div>
</section>

eConnect.Application/Views/ManageDepositRequest/Details.cshtml
@model eConnect.Model.ManageDeposit

@{ ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    string Receipt =  Model.Id + "/DepositReceipt/" + Model.RecieptDetail; }



<section class="section">
    <div class="card">
        <div class="card-body">
            <h6 class="text-primary mb-3"> Request Detail</h6>
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CSPName, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.CSPName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                @*<div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AccountDetail, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.AccountDetail, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                        </div>
                    </div>*@
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RequestedDate, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.RequestedDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                @*<div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                        </div>
                    </div>*@
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CurrentStatus, htmlAttributes: new { @class = "" })
                        @Html.DropDownList("Status", (SelectListItem[])ViewBag.EditedStatus, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
                @*<div class="row">*@
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CompletionDate, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.CompletionDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>

                @*</div>*@

            </div>

            <h6 class="text-primary mb-3"> Action</h6>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.RecieptDetail, htmlAttributes: new { @class = "" })
                        @Html.EditorFor(model => model.RecieptDetail, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                        @if (!string.IsNullOrEmpty(Model.RecieptDetail))
                        {
                            @*<a href="javascript:PreviewImage('@Model.RecieptDetail');">PreviewImage</a>*@
                            <a href="~/ImageViewer/Getimage/?Type=Deposit+&File=+@Receipt" target="_blank">PreviewImage</a>
                        }
                        else
                        {
                            <span style="color:red;">No image uploaded.</span>}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.VerifyReciept, htmlAttributes: new { @class = "" })
                        <br />
                        @Html.CheckBoxFor(model => model.VerifyReciept, new { @disabled = "disabled" })

                    </div>
                </div>


                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class="" })
                        @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    </div>
                </div>
                @*<div class="col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "required-field" })
                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control", } })

                        </div>
                    </div>*@
            </div>
            @*<div class="my-4 text-right">
                    <button class="btn btn-primary px-4" type="submit">Save</button>
                </div>*@
        <div class="text-left">
            @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
        </div>
        </div>
    </div>
</section>

<script>
    debugger;
    function PreviewImage(url) {
        var win = window.open();
        win.document.write("<iframe width='100%' height='100%' scrolling='no' src='" + url + "'></iframe>");
    }
</script>