eConnect.Application/Controllers/DepositRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConnect.DataAccess;
using eConnect.Model;
using eConnect.Logic;
using System.IO;
using System.Configuration;
using eConnect.Application.Models;
using NLog;
namespace eConnect.Application.Controllers
{
    public class DepositRequestController : Controller
    {

        private static Logger logger = LogManager.GetLogger("EConnectLogRules");
        string DepositStartTime, DepositEndTime = string.Empty;
        string UserFilePath = System.Web.HttpContext.Current.Server.MapPath(Convert.ToString(ConfigurationManager.AppSettings["DepositFilePath"]));
        string Email = ConfigurationManager.AppSettings["ToEmailid"].ToString();
        List<SelectListItem> RequestType = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Select RequestType", Value = "" },
                new SelectListItem { Text = "Withdrawal", Value = "1" },
                new SelectListItem { Text = "Deposit", Value = "2" },

            };
        List<SelectListItem> Status = new List<SelectListItem>()
            {

                new SelectListItem { Text = "Select Status", Value = "" },
                new SelectListItem { Text = "In-Progress", Value = "2" },
                 new SelectListItem { Text = "Not Started", Value = "5" },
                new SelectListItem { Text = "Completed", Value = "3" },

            };
        // GET: DepositRequest
        public ActionResult Index()

        {

            RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
            ViewBag.RequestType = RequestType;
            var tblDepositDetails = raiseRequest.GetDepositDetailsByCSPID(Convert.ToInt32(Session["CSPID"].ToString()));
            // var tblDepositDetails = raiseRequest.GetDepositDetails();
            bool flag = Convert.ToBoolean(TempData["flag"]);
            if (flag == true)
            {
                tblDepositDetails = TempData["searchdata"] as List<tblDepositRequest>;
            }
            return View(tblDepositDetails.ToList().OrderByDescending(x => x.DepositeRequestId));
        }
        public ActionResult IndexSearch(string Requestid, string RequestType, string Requesteddte, string Completiondte)
        {
            int Reqid = 0, ReqType = 0;
            RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
            ViewBag.RequestType = RequestType;
            if (Requestid == "")
            {
                Reqid = 0;
            }
            else
            {
                Reqid = Convert.ToInt32(Requestid);
            }
            if (RequestType == "")
            {
                ReqType = 0;
            }
            else
            {
                ReqType = Convert.ToInt32(RequestType);
            }
            var tblDepositDetails = raiseRequest.GetDepositDetailsSearch(Reqid, ReqType, Requesteddte, Completiondte);
            TempData["searchdata"] = tblDepositDetails.ToList();
            TempData["flag"] = true;
            return RedirectToAction("Index");
        }
        public ActionResult Create()
        {
            try
            {
                ViewBag.RequestType = RequestType;
                ViewBag.Status = Status;
            }
            catch (Exception ex)
            {
                logger.Error("Create Deposit Request" +" " +ex.Message);

            }
            return View();
        }

        public bool CheckWindow()
        {
            WindowTimingLogic OtrLogic = new WindowTimingLogic();
            var dt = OtrLogic.GetCurrentActiveWindow();
            if (dt.Count > 0)
            {
                DateTime dtStart = Convert.ToDateTime(dt[0].StartTime);
                DateTime dtEnd = Convert.ToDateTime(dt[0].EndTime);
                DateTime current = DateTime.Now;
                DepositStartTime = dt[0].StartTime;
                DepositEndTime = dt[0].EndTime;
                if (current.Ticks > dtStart.Ticks && current.Ticks < dtEnd.Ticks)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return true;
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Deposit deposit)
        {
            RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
            ViewBag.RequestType = RequestType;
            ViewBag.Status = Status;
            if (ModelState.IsValid)
            {
                int UserId = Convert.ToInt32(Session["CSPID"]);
                //Convert.ToInt32(Session["UserID"]);
                bool chktiming = CheckWindow();

                if (chktiming == true)
                {
                    long UserID = raiseRequest.AddDepositDetails(deposit, UserId);
                    string path = Path.Combine(UserFilePath, UserID.ToString());
                    if (deposit.Reciept != null)
                    {
                        string fpath = CheckDirectory(path, "DepositReceipt", deposit.Reciept);
                        deposit.Reciept.SaveAs(fpath);
                    }
                    //**EmailNotification**//
                    UserCSPDetailLogic objUserCSPDetailLogic = new UserCSPDetailLogic();
                    UserCSPDetail UserCSPDetail = objUserCSPDetailLogic.GetUserCSPDetailByID(Convert.ToInt32(UserId));
                    EmailNotification emailNotification = new EmailNotification();
                    emailNotification.SendEmail(Email, 2, UserCSPDetail, deposit.Amount.ToString(), deposit.BankDepositDate, "", "", "");
                    //*******************//
                }
                else
                {
                    TempData["TimingWindowMessage"] = "Deposit Request Window has been closed.Please raise the request between " + DepositStartTime + " to " + DepositEndTime;
                    return View(deposit);
                }
                return RedirectToAction("Index");
            }


            return View(deposit);
        }

        public ActionResult Edit(int? id)
        {
            //Deposit objDeposit = new Deposit();
            //return View(objDeposit);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
            Deposit objDeposit = raiseRequest.GetDepositDetailByID((int)id);
            Session["Imagereceipt"] = objDeposit.Recieptpic;
            if (objDeposit == null)
            {
                return HttpNotFound();
            }

            var ReqTypes = new[]
             {
                new SelectListItem(){Value = "1", Text= "Withdrawal"},
                new SelectListItem(){Value = "2", Text= "Deposit"},
            };

            var selectedRequestType = ReqTypes.FirstOrDefault(d => d.Value == objDeposit.RequestType.ToString());
            if (selectedRequestType != null)
                selectedRequestType.Selected = true;
            ViewBag.RequestType = ReqTypes;

            var Status = new[]
            {

                new SelectListItem { Text = "In-Progress", Value = "2" },
                new SelectListItem { Text = "Not Started", Value = "5" },
                new SelectListItem { Text = "Completed", Value = "3" },
            };
            var selectedStatus = Status.FirstOrDefault(d => d.Value == objDeposit.Status.ToString());
            if (selectedStatus != null)
                selectedStatus.Selected = true;
            ViewBag.EditStatus = Status;
            return View(objDeposit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Deposit deposit)
        {
            string Image = "";
            if (deposit.Reciept == null)
            {
                Image = Session["Imagereceipt"].ToString();
                deposit.Recieptpic = Image;
                ModelState.Remove("Reciept");
            }
            if (ModelState.IsValid)
            {

                string fpath = string.Empty;
                RaiseRequestLogic raiseRequestLogic = new RaiseRequestLogic();
                raiseRequestLogic.UpdateDepositDetail(deposit);
                string path = Path.Combine(UserFilePath, deposit.Id.ToString());
                if (deposit.Reciept != null)
                {
                    string fppath = CheckDirectory(path, "DepositReceipt", deposit.Reciept);
                    deposit.Reciept.SaveAs(fppath);
                }

                TempData["Message"] = "Record submitted successfully";
                return RedirectToAction("Index");
            }
            return View(deposit);
        }
        public string CheckDirectory(string path, string filetype, HttpPostedFileBase postedfile)
        {
            string fullpath = string.Empty;
            fullpath = Path.Combine(path, filetype);
            if (!Directory.Exists(fullpath))
            {
                Directory.CreateDirectory(fullpath);
            }
            fullpath = fullpath + "\\" + Path.GetFileName(postedfile.FileName);
            return fullpath;
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaiseRequestLogic raiseRequest = new RaiseRequestLogic();
            Deposit objDeposit = raiseRequest.GetDepositDetailByID((int)id);
            if (objDeposit == null)
            {
                return HttpNotFound();
            }
            var RequestTypes = new[]
            {
                new SelectListItem(){Value = "1", Text= "Withdrawal"},

eConnect.Application/Views/DepositRequest/Create.cshtml
@model eConnect.Model.Deposit

@{ ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml"; }



@using (Html.BeginForm("Create", "DepositRequest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

                <section class="section">
                    <div class="card">
                        <div class="card-body">
                            @*<h6 class="text-primary mb-3"> Personal Details</h6>*@
                            <div class="row">

                                @*<div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "required-field" })
                @Html.DropDownList("RequestType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
            </div>
        </div>*@

                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "required-field" })
                                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @*<div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "required-field" })
                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@
                                @*<div class="row">*@
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.BankDepositReceipt, htmlAttributes: new { @class = "required-field" })
                                        <input type="file" id="Reciept" name="Reciept" class="btn btn-outline-primary btn-block fileup-btn" onchange="show(this)" />
                                        @Html.ValidationMessageFor(model => model.Reciept, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.BankDepositDate, htmlAttributes: new { @class = "required-field" })
                                        <input type="date" id="BankDepositDate" name="BankDepositDate" class="form-control" />
                                        @Html.ValidationMessageFor(model => model.BankDepositDate, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                              

                            </div>
                            
                            <div class="my-4 text-right">
                                <button class="btn btn-primary px-4" type="submit">Save</button> |   @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                            </div>
                        </div>
                    </div>
                </section>}
@if (TempData["Message"] != null)
{
<script type="text/javascript">
        $(function () {
            alert("@TempData["Message"]")
        });
</script>
}

eConnect.Application/Views/DepositRequest/Edit.cshtml
@model eConnect.Model.Deposit

@{ ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    string Receipt = Model.Id + "/DepositReceipt/" + Model.Recieptpic;
    //string Receipt = @System.Web.Configuration.WebConfigurationManager.AppSettings["DepositFilePath"] + Model.Id + "\\DepositReceipt\\" + Model.Recieptpic;
    }
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "DepositRequest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)
                                                <section class="section">
                                                    <div class="card">
                                                        <div class="card-body">
                                                            @*<h6 class="text-primary mb-3"> Personal Details</h6>*@
                                                            <div class="row">

                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        <div class="form-group">
                                                                            @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "required-field" })
                                                                            @*@Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })*@
                                                                            @Html.DropDownList("RequestTypes", (SelectListItem[])ViewBag.RequestType, htmlAttributes: new { @class = "form-control" })
                                                                            @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "required-field" })
                                                                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @maxlength = "10" } })
                                                                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                                                    </div>
                                                                </div>
                                                                @*<div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "required-field" })
                                                                        @Html.DropDownList("Status", (SelectListItem[])ViewBag.EditStatus, htmlAttributes: new { @class = "form-control" })
                                                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                                                    </div>
                                                                </div>*@
                                                                @*<div class="row">*@
                                                                <div class="col-md-4">
                                                                    <div class="form-group">
                                                                        @Html.LabelFor(model => model.BankDepositReceipt, htmlAttributes: new { @class = "required-field" })
                                                                        <input type="file" id="Reciept" name="Reciept" class="btn btn-outline-primary btn-block fileup-btn" onchange="show(this)" />
                                                                        @if (!string.IsNullOrEmpty(Model.Recieptpic))
                                                                        {
                                                                            @*<a href="javascript:PreviewImage('@Model.Recieptpic');">PreviewImage</a>*@
                                                                            <a href="~/ImageViewer/Getimage/?Type=Deposit+&File=+@Receipt" target="_blank">PreviewImage</a>
                                                                        }
                                                                        else
                                                                        {
                                                                            <span style="color:red;">No image uploaded.</span>
                                                                        }

                                                                    </div>
                                                                </div>

                                                                @*</div>*@

                                                            </div>

                                                            <div class="my-4 text-right">
                                                                <button class="btn btn-primary px-4" type="submit">Save</button>
                                                            </div>
                                                            <div class="text-left">
                                                                @Html.ActionLink("Cancel", "Index", "Menu", new { @class = "btn btn-dark px-4 mr-2" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </section>
                                                }
<script>
    debugger;
    function PreviewImage(url) {
        var win = window.open();
        win.document.write("<iframe width='100%' height='100%' scrolling='no' src='" + url + "'></iframe>");
    }
</script>

eConnect.Application/Views/DepositRequest/Index.cshtml
@model IEnumerable<eConnect.DataAccess.tblDepositRequest>

@{ ViewBag.Title = "Deposit Request";
    Layout = "~/Views/Shared/_LayoutMain.cshtml"; }

    <section class="section">
        @*<h2></h2>*@



        @using (@Html.BeginForm("IndexSearch", "DepositRequest", FormMethod.Get))
        {@Html.AntiForgeryToken()
        <div class="card">
            <div class="card-header">
                <h4><span class="toggle-collapse" id="toggle" data-toggle="collapse" href="#filter" role="button" aria-expanded="true" aria-controls="filter"></span> Filter</h4>
            </div>
            <div class="card-body collapse show" id="filter">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Request Id</label>
                            <input type="text" id="Requestid" name="Requestid" class="form-control" value="@Request["Requestid"]">
                        </div>
                    </div>
                    @*<div class="col-md-3">
                        <div class="form-group">
                            <label>Request Type</label>
                            @Html.DropDownList("RequestType", (IEnumerable<SelectListItem>)ViewBag.RequestType, new { @class = "form-control" })
                        </div>
                    </div>*@
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Requested Date</label>
                            <input type="date" id="Requesteddte" name="Requesteddte" class="form-control" value="@Request["Requesteddte"]">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Completion Date</label>
                            <input type="date" id="Completiondte" name="Completiondte" class="form-control" value="@Request["Completiondte"]">

                        </div>
                    </div>


                    <div class="col-md-3 mt-md-4 pt-1">
                        @*<button class="btn btn-dark px-4 mr-2">Cancel</button>*@
                        <button type="submit" class="btn btn-primary px-4">Search</button>
                    </div>

                </div>
            </div>
        </div>}
        <p>
            @*@Html.ActionLink("Create New", "Create")*@
            @Html.ActionLink("Create New", "Create", "Menu", new { @class = "btn btn-primary px-4" })
        </p>
        <div class="card">

            <div class="card-body">


                <div class="table-responsive">
                    <div class="table-actions">
                        @*<a href="#" data-toggle="tooltip" title="Download Excel"><i class="mdi mdi-file-excel mdi-24px"></i></a>*@
                    </div>
                    <table class="table table-striped" id="table-2">
                        <thead>
                            <tr>
                                <!--<th>
                                RequestedID-->
                                @*@Html.DisplayNameFor(model => model.RequestId)*@
                                <!--</th>-->
                                <th>
                                    RequestedType
                                    @*@Html.DisplayNameFor(model => model.RequestId)*@
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RequestedDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CompletionDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th> Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.DepositeRequestId)
                                    </td>*@

                                    @if (item.RequestType.Equals(1))
                                    {
                                        <td>Withdrawal</td>

                                    }
                                    else
                                    {
                                        <td>Deposit</td>
                                    }
                                    @*@Html.DisplayFor(modelItem => item.RequestType)*@

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>
                                    <td>
                                        @*@Html.Label(@item.RequestedDate.Value.ToString("dd MMM yyyy"))*@

                                        @Html.DisplayFor(modelItem => item.RequestedDate)
                                    </td>
                                    <td>

                                        @if (item.CompletionDate != null)
                                        {
                                            @*@Html.Label(@item.CompletionDate.Value.ToString("dd MMM yyyy"))*@

                                            @Html.DisplayFor(modelItem => item.CompletionDate)
                                        }
                                        @*@Html.DisplayFor(modelItem => item.CompletionDate)*@
                                    </td>
                                    @if (item.Status.Equals(1))
                                    {
                                        <td>Open</td>

                                    }
                                    else if (item.Status.Equals(3))
                                    {
                                        <td>Close</td>
                                    }
                                    else if (item.Status.Equals(7))
                                    {
                                        <td>Rejected</td>
                                    }
                                    <td>
                                        @*@Html.ActionLink("Edit", "Edit", new { id = item.DepositeRequestId }) |*@
                                        @Html.ActionLink("Details", "Details", new { id = item.DepositeRequestId }) @*|
                                        @Html.ActionLink("Delete", "Delete", new { id = item.DepositeRequestId })*@
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </section>